name: tugasprojekcard
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.18.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  google_fonts: ^3.0.1
  carousel_slider: ^4.2.1
  sizer: ^2.0.15
  responsive_sizer: ^3.1.1
  carousel_indicator: ^1.0.6
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_database: ^10.0.7
  rflutter_alert: ^2.0.4
dependency_overrides:
  intl: ^0.18.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true